-- +goose Up
-- u_user: ユーザー情報
CREATE TABLE u_user (
    user_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_name CHAR(36) NOT NULL UNIQUE,
    nickname VARCHAR(255) NOT NULL,
    status VARCHAR(4096) NOT NULL DEFAULT "",
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- +goose Down
DROP TABLE IF EXISTS u_user;
